name: Deploy Yii2 App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files after checkout
      run: |
        ls -alh ./yii2-app  # List the contents to ensure Dockerfile is there

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t anshu1w/yii2-app:latest -f ./yii2-app/Dockerfile ./yii2-app
        docker push anshu1w/yii2-app:latest

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull anshu1w/yii2-app:latest
          docker stack deploy -c /home/ec2-user/devops-yii2-swarm/docker/docker-compose.yml yii2app
